### ISSUE TITLE
How would you recommend using this module in a NodeJS project?

### ISSUE THREAD

**Issue by FelixFortis** [ratson/factory-bot#5]
Hello! JS newbie here.

All of the examples are all from a single file, so I don't understand what to `modules.exports =` in order to use a factory in my specs.

I'm also using ES5.

Happy to make a PR to update the docs if someone can point me in the right direction.

How do I export this definition?

`spec/factories/user.js`

    const factory = require('factory-bot').factory;
    factory.setAdapter(new FactoryBot.MongooseAdapter());
    const User = require('../models/user');

    factory.define('user', User, { 
      username: 'Bob',
      expired: false
    });
    factory.extend('user', 'expiredUser', {
      expired: true
     });

And then how do I use my export here when making `sampleUsers`?

`spec/controllers/user.js`

    const reqs = require("../support/require")

    describe("GET /users", () => {
      describe("index", () => {
        var data = {};

        var sampleUsers = factory.createMany('user', 5);

        beforeEach((done) => {
          reqs.Request.get(/users", (error, response, body) => {
            data.status = response.statusCode;
            data.body = JSON.parse(body);
            done();
          });
        });

        it("returns a 200 response status", () => {
          expect(data.status).toBe(200);
        });
        it("responds with the users collection", async () => {
              expect(data.body.users).toBe(sampleUsers);
        });
      });
    });

**Comment by monkbroc** [comment]
Here's the pattern I use:

I create a `test-setup.js` which sets up factory-bot
```
# test-setup.js
const chai = require('chai');
const expect = chai.expect;

const mongoose = require('mongoose');
const FactoryBot = require('factory-bot');
const factory = FactoryBot.factory;
factory.setAdapter(new FactoryBot.MongooseAdapter());

/**
 * Connect to the test database
 * @returns {Promise} Resolves when the database is connected
 */
function connect() {
	return Promise.resolve().then(() => {
		if (!mongoose.connection.readyState) {
			return mongoose.connection.openUri('mongodb://localhost/mongoose-models');
		}
	});
}

/* Global test setup */
before(() => connect());
afterEach(() => {
	return factory.cleanUp();
});

module.exports = {
	chai,
	expect,
	mongoose,
	factory,
	connect
};
```

Then for each model, I create a factory file:
```
# User.factory.js
const { mongoose, factory } = require('../test/test-setup');
const User = require('./User')(mongoose);

factory.define('user', User, {
	email: factory.chance('email'),
});
```

Then I create a model test:
```
# User.test.js
const { expect, factory } = require('../test/test-setup');
require('./User.factory');

describe('User', () => {
	it('creates a valid user', () => {
		return factory.create('user');
	});

	// add additional tests and check results using expect
});
```

Finally I use my factory in integration tests:
```
# UserController.test.js
require('../models/User.factory');

describe("GET /users", () => {
// create users and run test
});
```

Does that help?
