### ISSUE TITLE
creating a record with its associations?

### ISSUE THREAD

**Issue by Trevoke** [ratson/factory-bot#6]
It's possible that I'm misunderstanding the readme, but.. It seems this is not possible? Right now in my tests I have to create the topmost record, then I have to create the next one and pass the id in?
I can successfully `build` but not `create`. I'm using the Sequelize adapter.

Please let me know if this should be possible (and what shape makes it possible).
... Also if it's either `build` or `create`, let me know that as well (i.e. if I have to choose between `assoc` and `assocAttrs`).

**Comment by ratson** [comment]
@Trevoke Would you post the code how are you using `build` and `create` for reference?

**Comment by Trevoke** [comment]
Hi - I've moved on to another project and I no longer have access to this code, I'm afraid. Sorry. You can close this if you like, I suppose.
